version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: python src/api/main.py
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.3.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    command: mlflow server --host 0.0.0.0 --backend-store-uri /mlruns
    restart: unless-stopped