name: forecast-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - streamlit>=1.22.0
  - pandas>=1.3.0
  - numpy>=1.21.0
  - plotly>=5.10.0
  - requests>=2.27.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pyjwt>=2.4.0
  - altair>=4.2.0
  - pillow>=9.0.0
  - python-dotenv>=0.20.0
  - watchdog>=2.1.0 