name: Deploy MLOps Sales Forecasting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for tags to be fetched for versioning
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
    
    - name: Run tests
      run: |
        pytest
    
    - name: Deploy to Streamlit Cloud
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}
      run: |
        echo "Deployment to Streamlit Cloud is handled automatically when connected to GitHub."
        echo "Ensure your repository is connected in Streamlit Cloud dashboard." 